/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.54).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Student;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2024-03-08T12:13:16.917553477Z[GMT]")
@Validated
public interface StudentApi {

    @Operation(summary = "", description = "To fetch student", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "200 response", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Student.class))) })
    @RequestMapping(value = "/student",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Student>> studentGet();


    @Operation(summary = "", description = "To Add Student", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "201 response") })
    @RequestMapping(value = "/student",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Student> studentPost(@Parameter(in = ParameterIn.DEFAULT, description = "structure of Student", required=true, schema=@Schema()) @Valid @RequestBody Student body
);

}

